<div style="width: 100%; position: relative; display: table; font-size: 12px;">
    <div style="display: table-cell; width: 33%; text-align: center; vertical-align: middle;">
        House No 931 Street No 91 I-8/4, Islamabad,
    </div>
    <div style="display: table-cell; width: 33%; text-align: center; vertical-align: middle;">
        <?php echo 'Generated at: ' . now(); ?>
    </div>
    <div style="display: table-cell; width: 33%; text-align: center; vertical-align: middle;">
        Generated by: {{ \Auth::user()->name }}
    </div>
</div>
