<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Restore deleted accounting records.
     *
     * Important:
     * 1. Take a fresh database backup before running this migration.
     * 2. Run this first on a staging copy of the live database.
     * 3. The journal_entries data supplied with the request duplicated the
     *    student_receipts columns, so journal_entries are intentionally not
     *    inserted here. Add the real journal_entries rows separately.
     */
    public function up(): void
    {
        DB::transaction(function (): void {
            /*
             * Parent records must be restored before child records.
             * insertOrIgnore() makes the migration safe to rerun when the
             * primary-key record already exists.
             */
            DB::table('challans')->insertOrIgnore([
                [
                    'id' => 110748,
                    'student_id' => 4458,
                    'class_id' => 23,
                    'rollno' => 4078,
                    'challanNo' => 208006,
                    'concession_id' => 397,
                    'challan_date' => '2026-05-04',
                    'fee_month' => '2026-07-01',
                    'other_months' => '2026-07-01',
                    'challan_type' => 'Advance',
                    'issue_date' => '2026-06-26',
                    'due_date' => '2026-07-08',
                    'remarks' => null,
                    'paid_amount' => 11421,
                    'total_amount' => 18029,
                    'concession_amount' => 3606,
                    'status' => 'Partial Paid',
                    'temp_status' => null,
                    'paid_date' => '2025-09-18',
                    'add_receipt' => null,
                    'voucher_id' => 273803,
                    'owned_by' => 7,
                    'created_by' => 2,
                    'session_id' => 2,
                    'created_at' => '2026-05-04 17:44:55',
                    'updated_at' => '2026-05-19 18:47:40',
                ],
                [
                    'id' => 107085,
                    'student_id' => 4458,
                    'class_id' => 23,
                    'rollno' => 4078,
                    'challanNo' => 204627,
                    'concession_id' => 397,
                    'challan_date' => '2026-02-01',
                    'fee_month' => '2026-02-01',

                    // Inferred from head price 90,145 = 18,029 x 5 months.
                    // Verify this against the backup before running.
                    'other_months' => '2026-02-01,2026-03-01,2026-04-01,2026-05-01,2026-06-01',

                    'challan_type' => 'Regular',
                    'issue_date' => '2026-01-26',
                    'due_date' => '2026-02-09',
                    'remarks' => null,
                    'paid_amount' => 72115,
                    'total_amount' => 75721,
                    'concession_amount' => 3606,
                    'status' => 'Paid',
                    'temp_status' => null,
                    'paid_date' => '2025-09-18',
                    'add_receipt' => null,
                    'voucher_id' => 261898,
                    'owned_by' => 7,
                    'created_by' => 2,
                    'session_id' => 2,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:43:16',
                ],
                [
                    'id' => 95825,
                    'student_id' => 4458,
                    'class_id' => 23,
                    'rollno' => 4078,
                    'challanNo' => 200443,
                    'concession_id' => 397,
                    'challan_date' => '2026-01-07',
                    'fee_month' => '2026-01-07',
                    'other_months' => null,
                    'challan_type' => 'Regular',
                    'issue_date' => '2025-12-26',
                    'due_date' => '2026-01-08',
                    'remarks' => null,
                    'paid_amount' => 24423,
                    'total_amount' => 28029,
                    'concession_amount' => 3606,
                    'status' => 'Paid',
                    'temp_status' => null,
                    'paid_date' => '2025-09-18',
                    'add_receipt' => null,
                    'voucher_id' => 230086,
                    'owned_by' => 7,
                    'created_by' => 2,
                    'session_id' => 2,
                    'created_at' => '2026-01-07 13:33:17',
                    'updated_at' => '2026-04-16 15:04:40',
                ]
            ]);

            DB::table('challan_heads')->insertOrIgnore([
                [
                    'id' => 143845,
                    'challan_id' => 95825,
                    'head_id' => 2,
                    'price' => 18029,
                    'concession' => 3606,
                    'paid' => 14423,
                    'created_at' => '2026-01-07 13:33:17',
                    'updated_at' => '2026-03-26 18:44:10',
                ],
                [
                    'id' => 143846,
                    'challan_id' => 95825,
                    'head_id' => 3,
                    'price' => 10000,
                    'concession' => 0,
                    'paid' => 10000,
                    'created_at' => '2026-01-07 13:33:17',
                    'updated_at' => '2026-03-26 18:44:10',
                ],
                [
                    'id' => 163693,
                    'challan_id' => 107085,
                    'head_id' => 2,
                    'price' => 90145,
                    'concession' => 18030,
                    'paid' => 72115,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:43:16',
                ],
                [
                    'id' => 170266,
                    'challan_id' => 110748,
                    'head_id' => 2,
                    'price' => 18029,
                    'concession' => 3606,
                    'paid' => 11421,
                    'created_at' => '2026-05-04 17:44:55',
                    'updated_at' => '2026-05-04 17:47:23',
                ],
            ]);

            DB::table('student_receipts')->insertOrIgnore([
                [
                    'id' => 158660,
                    'recipt_date' => '2025-09-18',
                    'challan_id' => 95825,
                    'student_id' => 4458,
                    'recipt_amount' => 24423.00,
                    'challan_amount' => 24423.00,
                    'late_amount' => 0.00,
                    'arrears' => 149074.00,
                    'bank_id' => 16,
                    'account_id' => null,
                    'received_by' => 7,
                    'voucher_id' => 261562,
                    'referance' => 'FRM HBL 23357901259303 956161139323',
                    'receive_type' => 'OL',
                    'owned_by' => 7,
                    'created_by' => 2,
                    'created_at' => '2026-03-26 18:44:10',
                    'updated_at' => '2026-03-26 18:44:11',
                ],
                [
                    'id' => 160920,
                    'recipt_date' => '2025-09-18',
                    'challan_id' => 107085,
                    'student_id' => 4458,
                    'recipt_amount' => 72115.00,
                    'challan_amount' => 72115.00,
                    'late_amount' => 0.00,
                    'arrears' => 150274.00,
                    'bank_id' => 16,
                    'account_id' => null,
                    'received_by' => 7,
                    'voucher_id' => 271236,
                    'referance' => 'FRM HBL 23357901259303 956161139323',
                    'receive_type' => 'OL',
                    'owned_by' => 7,
                    'created_by' => 2,
                    'created_at' => '2026-05-04 17:43:16',
                    'updated_at' => '2026-05-04 17:43:17',
                ],
                [
                    'id' => 160923,
                    'recipt_date' => '2025-09-18',
                    'challan_id' => 110748,
                    'student_id' => 4458,
                    'recipt_amount' => 11421.00,
                    'challan_amount' => 14423.00,
                    'late_amount' => 0.00,
                    'arrears' => 150274.00,
                    'bank_id' => 16,
                    'account_id' => null,
                    'received_by' => 7,
                    'voucher_id' => 271240,
                    'referance' => 'FRM HBL 23357901259303 956161139323',
                    'receive_type' => 'OL',
                    'owned_by' => 7,
                    'created_by' => 2,
                    'created_at' => '2026-05-04 17:47:23',
                    'updated_at' => '2026-05-04 17:47:23',
                ],
            ]);

            /*
             * The descriptions in the backup output were truncated by phpMyAdmin.
             * The migration preserves meaningful reconstructed descriptions instead
             * of storing literal trailing "..." text.
             */
            DB::table('journal_items')->insertOrIgnore([
                [
                    'id' => 606157,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 1,
                    'head' => 2,
                    'description' => 'Income Account: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 18029.00,
                    'entry_id' => 143845,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],
                [
                    'id' => 606158,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Account Receivable: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 18029.00,
                    'credit' => 0.00,
                    'entry_id' => 143845,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],
                [
                    'id' => 606159,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 17,
                    'head' => 2,
                    'description' => 'Discount Allowed Income: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 3606.00,
                    'credit' => 0.00,
                    'entry_id' => 143845,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],
                [
                    'id' => 606160,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Discount Allowed Receivable: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 3606.00,
                    'entry_id' => 143845,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],
                [
                    'id' => 606161,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 5,
                    'head' => 3,
                    'description' => 'Income Account: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 10000.00,
                    'entry_id' => 143846,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],
                [
                    'id' => 606162,
                    'journal' => 230086,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 4,
                    'head' => 3,
                    'description' => 'Account Receivable: Roll no 4458 Challan no 200443',
                    'memo' => null,
                    'debit' => 10000.00,
                    'credit' => 0.00,
                    'entry_id' => 143846,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-01-07 08:33:17',
                    'updated_at' => '2026-01-07 08:33:17',
                ],

                [
                    'id' => 712782,
                    'journal' => 261562,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Receive of Challan no: 200443 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 14423.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:44:11',
                    'updated_at' => '2025-09-18 17:44:11',
                ],
                [
                    'id' => 712783,
                    'journal' => 261562,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 4,
                    'head' => 3,
                    'description' => 'Receive of Challan no: 200443 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 10000.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:44:11',
                    'updated_at' => '2025-09-18 17:44:11',
                ],
                [
                    'id' => 712784,
                    'journal' => 261562,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 243,
                    'head' => 0,
                    'description' => 'Receive of Challan no: 200443 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 24423.00,
                    'credit' => 0.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:44:12',
                    'updated_at' => '2025-09-18 17:44:12',
                ],

                [
                    'id' => 714554,
                    'journal' => 261898,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 1,
                    'head' => 2,
                    'description' => 'Income Account: Roll no 4078 Challan no 204627',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 90145.00,
                    'entry_id' => 163693,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:05:23',
                ],
                [
                    'id' => 714555,
                    'journal' => 261898,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Account Receivable: Roll no 4078 Challan no 204627',
                    'memo' => null,
                    'debit' => 90145.00,
                    'credit' => 0.00,
                    'entry_id' => 163693,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:05:23',
                ],
                [
                    'id' => 714556,
                    'journal' => 261898,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 17,
                    'head' => 2,
                    'description' => 'Discount Allowed Income: Roll no 4078 Challan no 204627',
                    'memo' => null,
                    'debit' => 18030.00,
                    'credit' => 0.00,
                    'entry_id' => 163693,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:05:24',
                ],
                [
                    'id' => 714557,
                    'journal' => 261898,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Discount Allowed Receivable: Roll no 4078 Challan no 204627',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 18030.00,
                    'entry_id' => 163693,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-02-01 04:00:00',
                    'updated_at' => '2026-05-04 17:05:24',
                ],

                [
                    'id' => 755709,
                    'journal' => 271236,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Receive of Challan no: 204627 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 72115.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:43:16',
                    'updated_at' => '2025-09-18 17:43:16',
                ],
                [
                    'id' => 755710,
                    'journal' => 271236,
                    'user_id' => null,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 243,
                    'head' => 0,
                    'description' => 'Receive of Challan no: 204627 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 72115.00,
                    'credit' => 0.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:43:16',
                    'updated_at' => '2025-09-18 17:43:16',
                ],
                [
                    'id' => 755720,
                    'journal' => 271240,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Receive of Challan no: 208006 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 11421.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:47:23',
                    'updated_at' => '2025-09-18 17:47:23',
                ],
                [
                    'id' => 755721,
                    'journal' => 271240,
                    'user_id' => null,
                    'user_type' => 'Student',
                    'bank_id' => 16,
                    'account' => 243,
                    'head' => 0,
                    'description' => 'Receive of Challan no: 208006 - Bank: 50003 I-8',
                    'memo' => null,
                    'debit' => 11421.00,
                    'credit' => 0.00,
                    'entry_id' => null,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan Payment',
                    'is_discount' => 0,
                    'branch_id' => 7,
                    'created_at' => '2025-09-18 17:47:23',
                    'updated_at' => '2025-09-18 17:47:23',
                ],

                [
                    'id' => 763635,
                    'journal' => 273803,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 1,
                    'head' => 2,
                    'description' => 'Income Account: Roll no 4458 Challan no 208006',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 18029.00,
                    'entry_id' => 170266,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-05-19 18:47:40',
                    'updated_at' => '2026-05-19 18:47:40',
                ],
                [
                    'id' => 763636,
                    'journal' => 273803,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Account Receivable: Roll no 4458 Challan no 208006',
                    'memo' => null,
                    'debit' => 18029.00,
                    'credit' => 0.00,
                    'entry_id' => 170266,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 0,
                    'branch_id' => null,
                    'created_at' => '2026-05-19 18:47:40',
                    'updated_at' => '2026-05-19 18:47:40',
                ],
                [
                    'id' => 763637,
                    'journal' => 273803,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 17,
                    'head' => 2,
                    'description' => 'Discount Allowed Income: Roll no 4458 Challan no 208006',
                    'memo' => null,
                    'debit' => 3606.00,
                    'credit' => 0.00,
                    'entry_id' => 170266,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-05-19 18:47:40',
                    'updated_at' => '2026-05-19 18:47:40',
                ],
                [
                    'id' => 763638,
                    'journal' => 273803,
                    'user_id' => 4458,
                    'user_type' => 'Student',
                    'bank_id' => null,
                    'account' => 2,
                    'head' => 2,
                    'description' => 'Discount Allowed Receivable: Roll no 4458 Challan no 208006',
                    'memo' => null,
                    'debit' => 0.00,
                    'credit' => 3606.00,
                    'entry_id' => 170266,
                    'receipt_id' => null,
                    'head_ids' => null,
                    'types' => 'Challan',
                    'is_discount' => 1,
                    'branch_id' => null,
                    'created_at' => '2026-05-19 18:47:40',
                    'updated_at' => '2026-05-19 18:47:40',
                ],
            ]);
        });
    }

    /**
     * Remove only the rows restored by this migration.
     */
    public function down(): void
    {
        DB::transaction(function (): void {
            DB::table('journal_items')
                ->whereIn('id', [
                    606157, 606158, 606159, 606160, 606161, 606162,
                    712782, 712783, 712784,
                    714554, 714555, 714556, 714557,
                    755709, 755710, 755720, 755721,
                    763635, 763636, 763637, 763638,
                ])
                ->delete();

            DB::table('student_receipts')
                ->whereIn('id', [158660, 160920, 160923])
                ->delete();

            DB::table('challan_heads')
                ->whereIn('id', [143845, 143846, 163693, 170266])
                ->delete();

            DB::table('challans')
                ->whereIn('id', [110748, 107085, 95825, 64482])
                ->delete();
        });
    }
};
