<?php

return [
    'enabled' => env('LYNX_CUSTOM_SIDEBAR', false),
    'mobile_breakpoint' => 992,
    'flyout_width' => 280,
    'submenu_max_height' => 560,
    'items' => [
        [
            'key' => 'dashboard',
            'label' => 'Dashboard',
            'icon' => 'ti ti-layout-dashboard',
            'route_is' => ['dashboard', 'project.dashboard', 'hrm.dashboard', 'crm.dashboard', 'pos.dashboard', 'workspace.dashboard', 'client.dashboard.view'],
            'children' => [
                [
                    'key' => 'dashboard-overview',
                    'label' => 'Overview',
                    'icon' => 'ti ti-home',
                    'route_name' => 'dashboard',
                    'route_is' => ['dashboard'],
                ],
                [
                    'key' => 'dashboard-hrm',
                    'label' => 'HRM Overview',
                    'icon' => 'ti ti-users-group',
                    'route_name' => 'hrm.dashboard',
                    'route_is' => ['hrm.dashboard'],
                    'permissions' => ['show hrm dashboard'],
                ],
                [
                    'key' => 'dashboard-crm',
                    'label' => 'CRM Overview',
                    'icon' => 'ti ti-stairs-up',
                    'route_name' => 'crm.dashboard',
                    'route_is' => ['crm.dashboard'],
                    'permissions' => ['show crm dashboard'],
                ],
                [
                    'key' => 'dashboard-pos',
                    'label' => 'POS Overview',
                    'icon' => 'ti ti-shopping-cart',
                    'route_name' => 'pos.dashboard',
                    'route_is' => ['pos.dashboard'],
                    'permissions' => ['show pos dashboard'],
                ],
                [
                    'key' => 'dashboard-project',
                    'label' => 'Project Overview',
                    'icon' => 'ti ti-rocket',
                    'route_name' => 'project.dashboard',
                    'route_is' => ['project.dashboard'],
                    'permissions' => ['show project dashboard'],
                ],
                [
                    'key' => 'dashboard-workspace',
                    'label' => 'Workspace',
                    'icon' => 'ti ti-building-community',
                    'route_name' => 'workspace.dashboard',
                    'route_is' => ['workspace.dashboard'],
                ],
            ],
        ],
        [
            'key' => 'students',
            'label' => 'Students',
            'icon' => 'ti ti-school',
            'children' => [
                [
                    'key' => 'students-management',
                    'label' => 'Student Management',
                    'icon' => 'ti ti-student',
                    'children' => [
                        [
                            'key' => 'students-management-admissions',
                            'label' => 'Admissions',
                            'icon' => 'ti ti-user-plus',
                            'route_name' => 'registration.index',
                            'route_is' => ['registration.*', 'registration'],
                        ],
                        [
                            'key' => 'students-management-profiles',
                            'label' => 'Student Profile',
                            'icon' => 'ti ti-id',
                            'route_name' => 'enrollment.index',
                            'route_is' => ['enrollment.*', 'enrollment'],
                        ],
                        [
                            'key' => 'students-management-readmission',
                            'label' => 'Readmission',
                            'icon' => 'ti ti-refresh',
                            'route_name' => 'readmissionstudent.create',
                            'route_params' => ['flow_type' => 'readmission'],
                            'route_is' => ['readmissionstudent.*'],
                        ],
                        [
                            'key' => 'students-management-reenrollment',
                            'label' => 'Re-enrollment',
                            'icon' => 'ti ti-repeat',
                            'route_name' => 'readmissionstudent.create',
                            'route_params' => ['flow_type' => 're_enrollment'],
                            'route_is' => ['readmissionstudent.*'],
                        ],
                        [
                            'key' => 'students-management-reactivation',
                            'label' => 'Reactivation',
                            'icon' => 'ti ti-bolt',
                            'route_name' => 'readmissionstudent.create',
                            'route_params' => ['flow_type' => 'reactivation'],
                            'route_is' => ['readmissionstudent.*'],
                        ],
                        [
                            'key' => 'students-management-challans',
                            'label' => 'Challan Lists',
                            'icon' => 'ti ti-receipt-2',
                            'children' => [
                                [
                                    'key' => 'students-management-challans-registration',
                                    'label' => 'Registration Challans',
                                    'icon' => 'ti ti-receipt',
                                    'route_name' => 'registrationchallanlist',
                                    'route_is' => ['registration-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-admission',
                                    'label' => 'Admission Challans',
                                    'icon' => 'ti ti-file-invoice',
                                    'route_name' => 'admissionchallanlist',
                                    'route_is' => ['admission-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-regular',
                                    'label' => 'Regular Challans',
                                    'icon' => 'ti ti-file-dollar',
                                    'route_name' => 'regularchallanlist',
                                    'route_is' => ['regular-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-advance',
                                    'label' => 'Advance Challans',
                                    'icon' => 'ti ti-credit-card-pay',
                                    'route_name' => 'advancechallanlist',
                                    'route_is' => ['advance-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-withdrawal',
                                    'label' => 'Withdrawal Challans',
                                    'icon' => 'ti ti-file-alert',
                                    'route_name' => 'withdrawchallanlist',
                                    'route_is' => ['withdraw-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-transfer',
                                    'label' => 'Transfer Challans',
                                    'icon' => 'ti ti-arrows-transfer-up',
                                    'route_name' => 'transferchallanlist',
                                    'route_is' => ['transfer-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-readmission',
                                    'label' => 'Re-Admission Challans',
                                    'icon' => 'ti ti-receipt-off',
                                    'route_name' => 'readmissionchallanlist',
                                    'route_is' => ['readmission-challan*'],
                                ],
                                [
                                    'key' => 'students-management-challans-studypack',
                                    'label' => 'StudyPack Challans',
                                    'icon' => 'ti ti-book-2',
                                    'route_name' => 'studypackchallan.index',
                                    'route_is' => ['studypackchallan*'],
                                ],
                            ],
                        ],
                    ],
                ],
                [
                    'key' => 'students-setup',
                    'label' => 'Setup',
                    'icon' => 'ti ti-settings',
                    'children' => [
                        [
                            'key' => 'students-setup-register-option',
                            'label' => 'Register Option',
                            'icon' => 'ti ti-list-check',
                            'route_name' => 'registerOption.index',
                            'route_is' => ['registerOption*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-session',
                            'label' => 'Session Setup',
                            'icon' => 'ti ti-calendar-event',
                            'route_name' => 'session.index',
                            'route_is' => ['session*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-class',
                            'label' => 'Class Setup',
                            'icon' => 'ti ti-layers-intersect',
                            'route_name' => 'classes.index',
                            'route_is' => ['classes*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-section',
                            'label' => 'Class & Section Setup',
                            'icon' => 'ti ti-building-arch',
                            'route_name' => 'section.index',
                            'route_is' => ['section*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-bulk-billing',
                            'label' => 'Bulk Billing',
                            'icon' => 'ti ti-calculator',
                            'route_name' => 'bulk-billing.create',
                            'route_is' => ['bulk-billing*'],
                        ],
                        [
                            'key' => 'students-setup-fee-heads',
                            'label' => 'Fee Heads Setup',
                            'icon' => 'ti ti-tags',
                            'route_name' => 'fee_head.index',
                            'route_is' => ['fee_head*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-fee-structure',
                            'label' => 'Fee Structure Setup',
                            'icon' => 'ti ti-table',
                            'route_name' => 'class_wise_fee.index',
                            'route_is' => ['class_wise_fee*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-concession-policy',
                            'label' => 'Concession Policy Setup',
                            'icon' => 'ti ti-discount-2',
                            'route_name' => 'concession_policy.index',
                            'route_is' => ['concession_policy*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-studypacks',
                            'label' => 'Study Packs Setup',
                            'icon' => 'ti ti-books',
                            'route_name' => 'studypack.index',
                            'route_is' => ['studypack*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-setup-tax-slab',
                            'label' => 'Tax Slab Setup',
                            'icon' => 'ti ti-file-percent',
                            'route_name' => 'tax-slab.index',
                            'route_is' => ['tax-slab*'],
                            'permissions' => ['view spacetype'],
                        ],
                    ],
                ],
                [
                    'key' => 'students-formation',
                    'label' => 'Formation',
                    'icon' => 'ti ti-sitemap',
                    'children' => [
                        [
                            'key' => 'students-formation-import',
                            'label' => 'Student Import',
                            'icon' => 'ti ti-file-import',
                            'route_name' => 'student.import',
                            'route_is' => ['student.import'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-promotion',
                            'label' => 'Student Promotion',
                            'icon' => 'ti ti-transfer-in',
                            'route_name' => 'student-promotion.index',
                            'route_is' => ['student-promotion*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-bulk-section',
                            'label' => 'Bulk Section Update',
                            'icon' => 'ti ti-layout-grid',
                            'route_name' => 'section.bulkindex',
                            'route_is' => ['section.bulkindex'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-remove-late-fee',
                            'label' => 'Remove Late Fee',
                            'icon' => 'ti ti-clock-x',
                            'route_name' => 'remove-late-fee.index',
                            'route_is' => ['remove-late-fee*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-transfer',
                            'label' => 'Student Transfer',
                            'icon' => 'ti ti-arrows-transfer-down',
                            'route_name' => 'transferstudent.index',
                            'route_is' => ['transferstudent*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-bulk-transfer',
                            'label' => 'Bulk Student Transfer',
                            'icon' => 'ti ti-switch-horizontal',
                            'route_name' => 'bulk-transfer.index',
                            'route_is' => ['bulk-transfer*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-formation-concession',
                            'label' => 'Concession Application',
                            'icon' => 'ti ti-ticket-discount',
                            'route_name' => 'concession.create',
                            'route_is' => ['concession*'],
                        ],
                        [
                            'key' => 'students-formation-withdrawal',
                            'label' => 'Withdrawal Application',
                            'icon' => 'ti ti-user-off',
                            'route_name' => 'withdrawlstudent.create',
                            'route_is' => ['withdrawlstudent*'],
                        ],
                        [
                            'key' => 'students-formation-readmission',
                            'label' => 'Re-Admission',
                            'icon' => 'ti ti-refresh',
                            'route_name' => 'readmissionstudent.create',
                            'route_is' => ['readmissionstudent*'],
                        ],
                        [
                            'key' => 'students-formation-clearance',
                            'label' => 'Clearance Certificate',
                            'icon' => 'ti ti-certificate',
                            'route_name' => 'clearance.index',
                            'route_is' => ['clearance*', 'clearanceCertificate*'],
                        ],
                    ],
                ],
                [
                    'key' => 'students-reports',
                    'label' => 'Reports',
                    'icon' => 'ti ti-report-search',
                    'children' => [
                        [
                            'key' => 'students-reports-class-wise',
                            'label' => 'Class Wise',
                            'icon' => 'ti ti-school',
                            'route_name' => 'classwisefeereport',
                            'route_is' => ['classwisefeereport*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-branch-wise',
                            'label' => 'Branch Wise',
                            'icon' => 'ti ti-map-pin',
                            'route_name' => 'sessionBranchWise',
                            'route_is' => ['sessionBranchWise*', 'sessionMonthBranchWise*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-registration',
                            'label' => 'Registration',
                            'icon' => 'ti ti-file-description',
                            'route_name' => 'registrationdetailreport',
                            'route_is' => ['registrationdetailreport*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-admission',
                            'label' => 'Admission Listing',
                            'icon' => 'ti ti-list-details',
                            'route_name' => 'admissionlisting',
                            'route_is' => ['admissionlisting*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-average-monthly',
                            'label' => 'Average Monthly Report',
                            'icon' => 'ti ti-chart-bar',
                            'route_name' => 'average_monthly_report',
                            'route_is' => ['average-monthly-report*', 'average_monthly_report*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-challan',
                            'label' => 'Challan Reports',
                            'icon' => 'ti ti-receipt-2',
                            'children' => [
                                [
                                    'key' => 'students-reports-challan-pre',
                                    'label' => 'Monthly Pre-Challan',
                                    'icon' => 'ti ti-calendar-stats',
                                    'route_name' => 'monthlyprechallanreport',
                                    'route_is' => ['monthlyperchallanreport*', 'monthlyprechallanreport*'],
                                ],
                                [
                                    'key' => 'students-reports-challan-regular',
                                    'label' => 'Regular Challan',
                                    'icon' => 'ti ti-file-invoice',
                                    'route_name' => 'monthlychallanreport',
                                    'route_is' => ['monthlychallanreport*'],
                                ],
                                [
                                    'key' => 'students-reports-challan-advance',
                                    'label' => 'Advance Challan',
                                    'icon' => 'ti ti-file-dollar',
                                    'route_name' => 'advancechallanreport',
                                    'route_is' => ['advancechallanreport*'],
                                ],
                            ],
                        ],
                        [
                            'key' => 'students-reports-security',
                            'label' => 'Security Deposit',
                            'icon' => 'ti ti-shield-dollar',
                            'route_name' => 'student_security_report',
                            'route_is' => ['studentSecurityReport*', 'student_security_report*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-account-statement',
                            'label' => 'Account Statement',
                            'icon' => 'ti ti-file-text',
                            'route_name' => 'student_single_account',
                            'route_is' => ['student-single-account*'],
                            'permissions' => ['view spacetype'],
                        ],
                        [
                            'key' => 'students-reports-withdrawal',
                            'label' => 'Withdraw Listing',
                            'icon' => 'ti ti-file-minus',
                            'route_name' => 'student_withdrawl_listing',
                            'route_is' => ['student-withdarawl-listing*', 'student_withdrawl_listing*'],
                            'permissions' => ['view spacetype'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'hrm',
            'label' => 'HRM System',
            'icon' => 'ti ti-users-group',
            'children' => [
                [
                    'key' => 'hrm-overview',
                    'label' => 'Overview',
                    'icon' => 'ti ti-home',
                    'route_name' => 'hrm.dashboard',
                    'route_is' => ['hrm.dashboard'],
                    'permissions' => ['show hrm dashboard'],
                ],
                [
                    'key' => 'hrm-payroll',
                    'label' => 'Payroll Setup',
                    'icon' => 'ti ti-wallet',
                    'children' => [
                        [
                            'key' => 'hrm-payroll-setsalary',
                            'label' => 'Set Salary',
                            'icon' => 'ti ti-currency-rupee',
                            'route_name' => 'setsalary.index',
                            'route_is' => ['setsalary*'],
                        ],
                        [
                            'key' => 'hrm-payroll-proposal',
                            'label' => 'Salary Proposal',
                            'icon' => 'ti ti-report-money',
                            'route_name' => 'employee-salary-proporal.index',
                            'route_is' => ['employee-salary-proporal*'],
                        ],
                        [
                            'key' => 'hrm-payroll-payslip',
                            'label' => 'Payslip',
                            'icon' => 'ti ti-receipt-dollar',
                            'route_name' => 'payslip.index',
                            'route_is' => ['payslip*'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'user-management',
            'label' => 'User Management',
            'icon' => 'ti ti-user-cog',
            'children' => [
                [
                    'key' => 'user-management-users',
                    'label' => 'Users',
                    'icon' => 'ti ti-users',
                    'route_name' => 'users.index',
                    'route_is' => ['users*', 'user.userlog'],
                    'permissions' => ['manage user'],
                ],
                [
                    'key' => 'user-management-roles',
                    'label' => 'Roles',
                    'icon' => 'ti ti-shield-lock',
                    'route_name' => 'roles.index',
                    'route_is' => ['roles*'],
                    'permissions' => ['manage role'],
                ],
            ],
        ],
        [
            'key' => 'pos',
            'label' => 'POS',
            'icon' => 'ti ti-shopping-bag',
            'children' => [
                [
                    'key' => 'pos-overview',
                    'label' => 'Overview',
                    'icon' => 'ti ti-home',
                    'route_name' => 'pos.dashboard',
                    'route_is' => ['pos.dashboard'],
                    'permissions' => ['show pos dashboard'],
                ],
                [
                    'key' => 'pos-reports',
                    'label' => 'Reports',
                    'icon' => 'ti ti-chart-bar',
                    'children' => [
                        [
                            'key' => 'pos-reports-warehouse',
                            'label' => 'Warehouse Report',
                            'icon' => 'ti ti-building-warehouse',
                            'route_name' => 'report.warehouse',
                            'route_is' => ['reports-warehouse*', 'report.warehouse'],
                            'permissions' => ['manage pos'],
                        ],
                        [
                            'key' => 'pos-reports-purchase',
                            'label' => 'Purchase Daily/Monthly',
                            'icon' => 'ti ti-calendar-stats',
                            'route_name' => 'report.daily.purchase',
                            'route_is' => ['reports-daily-purchase*', 'reports-monthly-purchase*'],
                            'permissions' => ['manage pos'],
                        ],
                        [
                            'key' => 'pos-reports-pos',
                            'label' => 'POS Daily/Monthly',
                            'icon' => 'ti ti-report-analytics',
                            'route_name' => 'report.daily.pos',
                            'route_is' => ['reports-daily-pos*', 'reports-monthly-pos*'],
                            'permissions' => ['manage pos'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'workspace',
            'label' => 'Workspace',
            'icon' => 'ti ti-layout-dashboard',
            'children' => [
                [
                    'key' => 'workspace-dashboard',
                    'label' => 'Workspace Dashboard',
                    'icon' => 'ti ti-home',
                    'route_name' => 'workspace.dashboard',
                    'route_is' => ['workspace.dashboard'],
                ],
                [
                    'key' => 'workspace-asset-setup',
                    'label' => 'Asset Setup',
                    'icon' => 'ti ti-package',
                    'route_name' => 'account-assets.index',
                    'route_is' => ['account-assets*'],
                    'permissions' => ['view space'],
                ],
            ],
        ],
        [
            'key' => 'project-system',
            'label' => 'Project System',
            'icon' => 'ti ti-rocket',
            'children' => [
                [
                    'key' => 'project-system-overview',
                    'label' => 'Overview',
                    'icon' => 'ti ti-home',
                    'route_name' => 'project.dashboard',
                    'route_is' => ['project.dashboard'],
                    'permissions' => ['show project dashboard'],
                ],
                [
                    'key' => 'project-system-projects',
                    'label' => 'Projects',
                    'icon' => 'ti ti-folder',
                    'route_name' => 'projects.index',
                    'route_is' => ['projects*'],
                    'permissions' => ['manage project'],
                ],
                [
                    'key' => 'project-system-tasks',
                    'label' => 'Tasks',
                    'icon' => 'ti ti-list-check',
                    'route_name' => 'taskBoard.view',
                    'route_params' => ['list'],
                    'route_is' => ['taskboard*'],
                    'permissions' => ['manage project task'],
                ],
                [
                    'key' => 'project-system-setup',
                    'label' => 'Setup',
                    'icon' => 'ti ti-settings',
                    'children' => [
                        [
                            'key' => 'project-system-setup-stages',
                            'label' => 'Task Stages',
                            'icon' => 'ti ti-stack',
                            'route_name' => 'project-task-stages.index',
                            'route_is' => ['project-task-stages*'],
                            'permissions' => ['manage project task stage'],
                        ],
                        [
                            'key' => 'project-system-setup-bugstatus',
                            'label' => 'Bug Status',
                            'icon' => 'ti ti-bug',
                            'route_name' => 'bugstatus.index',
                            'route_is' => ['bugstatus*'],
                            'permissions' => ['manage bug status'],
                        ],
                    ],
                ],
            ],
        ],
        [
            'key' => 'accounting',
            'label' => 'Accounting System',
            'icon' => 'ti ti-cash',
            'show_when' => 'show_account',
            'children' => [
                [
                    'key' => 'accounting-banking',
                    'label' => 'Banking',
                    'icon' => 'ti ti-building-bank',
                    'children' => [
                        [
                            'key' => 'accounting-banking-account',
                            'label' => 'Account',
                            'icon' => 'ti ti-credit-card',
                            'route_name' => 'bank-account.index',
                            'route_is' => ['bank-account*'],
                            'permissions' => ['manage bank account'],
                        ],
                        [
                            'key' => 'accounting-banking-transfer',
                            'label' => 'Transfer',
                            'icon' => 'ti ti-transfer',
                            'route_name' => 'bank-transfer.index',
                            'route_is' => ['bank-transfer*'],
                            'permissions' => ['manage bank transfer'],
                        ],
                    ],
                ],
                [
                    'key' => 'accounting-vouchers',
                    'label' => 'Vouchers',
                    'icon' => 'ti ti-notebook',
                    'children' => [
                        [
                            'key' => 'accounting-vouchers-jv',
                            'label' => 'Journal Voucher',
                            'icon' => 'ti ti-clipboard-text',
                            'route_name' => 'journal-entry.index',
                            'route_is' => ['journal-entry*'],
                            'permissions' => ['manage journal entry'],
                        ],
                        [
                            'key' => 'accounting-vouchers-brv',
                            'label' => 'BRV',
                            'icon' => 'ti ti-receipt-refund',
                            'route_name' => 'bank-recipt-voucher.index',
                            'route_is' => ['bank-recipt-voucher*'],
                        ],
                        [
                            'key' => 'accounting-vouchers-bpv',
                            'label' => 'BPV',
                            'icon' => 'ti ti-receipt-2',
                            'route_name' => 'bank-payment-voucher.index',
                            'route_is' => ['bank-payment-voucher*'],
                        ],
                        [
                            'key' => 'accounting-vouchers-crv',
                            'label' => 'CRV',
                            'icon' => 'ti ti-receipt',
                            'route_name' => 'cash-recipt-voucher.index',
                            'route_is' => ['cash-recipt-voucher*'],
                        ],
                        [
                            'key' => 'accounting-vouchers-cpv',
                            'label' => 'CPV',
                            'icon' => 'ti ti-receipt-off',
                            'route_name' => 'cash-payment-voucher.index',
                            'route_is' => ['cash-payment-voucher*'],
                        ],
                    ],
                ],
                [
                    'key' => 'accounting-reports',
                    'label' => 'Reports',
                    'icon' => 'ti ti-chart-pie',
                    'children' => [
                        [
                            'key' => 'accounting-reports-ledger',
                            'label' => 'Ledger Summary',
                            'icon' => 'ti ti-report-money',
                            'route_name' => 'report.ledger',
                            'route_params' => [0],
                            'route_is' => ['report.ledger'],
                            'permissions' => ['ledger report'],
                        ],
                        [
                            'key' => 'accounting-reports-balance',
                            'label' => 'Balance Sheet',
                            'icon' => 'ti ti-balance-scale',
                            'route_name' => 'report.balance.sheet',
                            'route_is' => ['report.balance.sheet'],
                            'permissions' => ['balance sheet report'],
                        ],
                        [
                            'key' => 'accounting-reports-profit-loss',
                            'label' => 'Profit & Loss',
                            'icon' => 'ti ti-chart-line',
                            'route_name' => 'report.profit.loss',
                            'route_is' => ['report.profit.loss'],
                            'permissions' => ['income vs expense report'],
                        ],
                        [
                            'key' => 'accounting-reports-trial',
                            'label' => 'Trial Balance',
                            'icon' => 'ti ti-scale',
                            'route_name' => 'trial.balance',
                            'route_is' => ['trial.balance'],
                            'permissions' => ['trial balance report'],
                        ],
                    ],
                ],
                [
                    'key' => 'accounting-setup',
                    'label' => 'Accounting Setup',
                    'icon' => 'ti ti-adjustments',
                    'children' => [
                        [
                            'key' => 'accounting-setup-taxes',
                            'label' => 'Taxes',
                            'icon' => 'ti ti-percentage',
                            'route_name' => 'taxes.index',
                            'route_is' => ['taxes*'],
                            'permissions' => ['manage accounting permissions'],
                        ],
                        [
                            'key' => 'accounting-setup-print',
                            'label' => 'Print Settings',
                            'icon' => 'ti ti-printer',
                            'route_name' => 'print.setting',
                            'route_is' => ['print-setting*'],
                        ],
                    ],
                ],
            ],
        ],
    ],
];


