<table style="width: 100%; position: relative; font-size: 12px; border-collapse: collapse;">
    {{-- for addres --}}
    <tr>
        <td style="width: 70%; text-align: left; vertical-align: top; font-size: 10px;">
            <img style="max-width: 10px; max-height: 10px; vertical-align: middle; display: inline-block;" src="{{ asset('assets/images/location.png')}}" alt="location">
            &nbsp; <span style="font-size: 10px; vertical-align: middle; display: inline-block;">{{$employee->headOffice->address ?? 'House No 831 Street No 91 I-8/4, Islamabad, Pakistan'}}</span>
        </td>
        <td style="width: 20%; text-align: center; vertical-align: top; font-size: 10px;">
            <img style="max-width: 10px; max-height: 10px; vertical-align: middle; display: inline-block;" src="{{ asset('assets/images/call.png')}}" alt="phone"> 
            &nbsp; <span style="font-size: 10px; vertical-align: middle; display: inline-block;">{{$employee->headOffice->phone_no ?? '(051)4853745'}}</span>
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top; font-size: 10px;">
            <img style="max-width: 10px; max-height: 10px; vertical-align: middle; display: inline-block;" src="{{ asset('assets/images/email.png')}}" alt="email">
            &nbsp; <span style="font-size: 10px; vertical-align: middle; display: inline-block;">
                
    {{ $employee->userbranch->email ?? 'accounts@thelynxschool.edu.pk' }}
</span>
        </td>
    </tr>
    <tr><td colspan="3" style="height: 25px;"></td></tr>
    {{-- for generated by --}}
    <tr>
        <td style="width: 50%; text-align: left; vertical-align: top; font-size: 10px;">
            Generated by: {{ \Auth::user()->name }}
        </td>
        <td style="width: 50%; text-align: left; vertical-align: top;">
           
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top; font-size: 10px;">
            Generated at: {{ now()->format('d-m-Y H:i') }}
        </td>
    </tr>

</table>