<table style="width: 100%; position: relative; font-size: 12px; border-collapse: collapse;">
    <tr>
        <td style="width: 50%; text-align: left; vertical-align: top;">
            Generated by: {{ \Auth::user()->name }}
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            Generated at: {{ now()->format('d-m-Y H:i') }}
        </td>
    </tr>
    <tr>
        <td style="width: 50%; text-align: left; vertical-align: top;">
           
        </td>
        <td style="width: 50%; text-align: right; vertical-align: top;">
            
        </td>
    </tr>
</table>

<script type="text/php">
    if (isset($pdf)) {
        $font = $fontMetrics->getFont("Helvetica", "normal");
        $size = 10;
        $x = $pdf->get_width() - 120; // right-aligned, adjust as needed
        $y = 800; // just below the 'Generated at' line, adjust as needed
        $pdf->page_script(function($pageNumber, $pageCount, $pdf) use ($font, $size, $x, $y) {
            $pdf->text($x, $y, "Page $pageNumber of $pageCount", $font, $size);
        });
    }
</script>